
x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  test:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      mariadb: *healthy
    command: bundle exec rspec
    environment:
      RIGHTS_DATABASE_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"

  mariadb:
    image: ghcr.io/hathitrust/db-image
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]


volumes:
  gem_cache:
